### ISSUE TITLE
jUnit XML Importer does not handle empty test suites

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/ibutsu-server#75]
When an XML file has no `testcase` children in a `testsuite`, then the following exception occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/ibutsu_server/tasks/__init__.py", line 30, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/ibutsu_server/tasks/importers.py", line 95, in run_junit_import
    for testcase in testsuite.testcase:
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: testcase
```

**Comment by john-dupuy** [comment]
Fixed by #80
